export default {
 ownership:'I documented and completed the disassembly, desoldering, switch modification, PCB rework, foam fitting, and reassembly. The finished keyboard was checked across its switches, sliders, and diodes.',
 coverCaption:'The completed Project Robocop keyboard with new switches, keycaps, internal padding, and fitted case foam.',
 source:'Project Robocop Documentation, March 29, 2025, especially pp. 5–20 and the build sequence on pp. 23–35. The $189.50 figure is the documented project cost. Sound and feel were evaluated qualitatively.',
 sections:[
 {id:'starting-point',nav:'Starting point & goals',title:'Keeping the sound structure. Reworking the experience.',html:({paragraphs,figures})=>paragraphs([
 'The keyboard’s PCB and case were still functional, but the typing experience was poor. The switches felt inconsistent, scratchy, and sluggish; the keycaps were worn; and the unpadded case sounded hollow and rattled. I wanted to preserve the working foundation while rebuilding the mechanical and acoustic details around it.',
 'The target was specific to my preferences: tactile switches, a stiff and well-supported board, consistent feel, and a fuller sound with more emphasis on the lower frequencies. That meant treating the switches, PCB support, and case interior as one stack rather than expecting a single replacement part to solve everything.'
 ])+figures([['robocop-23-0','Starting condition: worn keycaps on a structurally sound keyboard.'],['robocop-24-0','After keycap removal and cleaning, before removing the original switches.']])},
 {id:'rework',nav:'Disassembly & PCB rework',title:'84 positions, 168 pins, and a board worth preserving.',html:({paragraphs,figures})=>paragraphs([
 'I removed the PCB and plate from the case and desoldered every original switch. With 84 positions and two switch pins per position, that meant 168 solder joints before the replacement switches could be installed. I cleaned the board with isopropyl alcohol and prepared each position for its new switch pad.',
 'Disassembly also exposed the fit constraints that would matter later: the battery, side sliders, screw standoffs, and surface-mounted components all needed clearance after padding was added. The case’s irregular internal geometry made a single rectangular foam insert unsuitable.'
 ])+figures([['robocop-25-0','Separating the PCB and plate assembly from the case.'],['robocop-25-1','The reverse of the PCB and the exposed case interior.']])+figureOrRows(figures)},
 {id:'switches',nav:'The switch-production process',title:'Making a small operation repeatable, 108 times.',html:({paragraphs,figures,table})=>paragraphs([
 'I modified 108 replacement switches in batches of 36. Each switch went through six major operations: opening, lubrication, spring replacement, spring lubrication, filming, and reassembly. Breaking the work into batches kept a long series of small manual tasks organized across multiple sessions.',
 'The switch work included lubrication on 14 surfaces, new 63.5 g double-stage springs, and thin polycarbonate films between the housing halves. The aim was more consistent motion and housing fit. A rack organized the lower housings, springs, and stems while the tops were kept together for reassembly.'
 ])+figures([['robocop-27-0','A disassembled switch, film, pad, lubricants, opener, stem holder, and brush.'],['robocop-28-0','Batch lubrication with the switch components organized in a work rack.']])+figures([['robocop-29-0','A thin switch film held in tweezers before installation.'],['robocop-30-0','Poron switch pads fitted to the PCB positions.']])+table('The repeatable switch workflow',['Operation','Purpose'],[['Open','Separate the housing without mixing or damaging the small parts.'],['Lubricate','Treat the contact surfaces for the intended smoothness and feel.'],['Replace springs','Establish the preferred spring behavior.'],['Lubricate springs','Address friction and spring-related noise.'],['Film','Improve the fit between the housing halves.'],['Reassemble','Check stem orientation and film position before closing the switch.']])},
 {id:'case',nav:'Foam, clearances & assembly',title:'The acoustic treatment still had to fit.',html:({paragraphs,figures})=>paragraphs([
 'I fitted poron pads at the switch positions and cut 4 mm EVA foam into interlocking pieces for the case. The foam had to fill useful space while leaving the battery, standoffs, sliders, and electronics unobstructed. Some of the switch pads also needed trimming to fit their locations.',
 'Repeated test fits were necessary because the added material changed the internal stack. I revised the foam around the side controls and surface-mounted components, then aligned the replacement switches with the plate and PCB, checked their pins, and soldered them in place.'
 ])+figures([['robocop-31-0','The case before the complete foam treatment.'],['robocop-31-1','Cutting and fitting the foam around the internal hardware.'],['robocop-32-0','The fitted foam layers with clearances around the constrained areas.']],'three')+figures([['robocop-33-0','Replacement switches soldered into the PCB and plate assembly.'],['robocop-34-0','The reassembled keyboard before the keycaps were installed.']])},
 {id:'result',nav:'Verification & finished result',title:'A finished object with the small details resolved.',html:({paragraphs})=>paragraphs([
 'I reconnected the battery, positioned the sliders, tightened the case, and checked every switch, slider, and diode before installing the new keycaps. The complete restoration cost $189.50 in the documented materials and supplies.',
 'The result was a working keyboard rebuilt around my preferred feel and sound. Those improvements were qualitative; I did not conduct an instrumented acoustic comparison. The documented engineering work is the repeatable switch process, circuit-board rework, clearance management, and final functional verification.',
 'Compared with a rocket or robot, this was a small system. It still rewarded the same habits: keep the existing constraints visible, organize repetitive work, check fit before final assembly, and verify that the finished object works as a whole.'
 ])}
 ]
};
function figureOrRows(figures){return figures([['robocop-26-0','The switches, plate, and PCB after desoldering and separation.']],'natural');}
