export default {
 coverCaption:'Fully assembled and connected Atlas flight computer before a full-system load test.',
 ownership:'I designed the custom PCB, selected and integrated its components, developed its layout in KiCad, inspected the first bare boards, revised the design, and brought up the assembled hardware. Atlas is an independent embedded-systems project intended for flight experiments and state-estimation research.',
 source:'Project account based on Engineering Portfolio Raw, pp. 43–69, with the current assembled-board testing update. The original annotated layout is reproduced directly. Bench functionality, planned software, and flight qualification are distinguished throughout.',
 sections:[
 {id:'purpose',nav:'System purpose & architecture',title:'Building the electronics behind the flight.',html:({paragraphs,figure,table})=>paragraphs([
 'After integrating commercial avionics in Hat Trick and Apollyon, I wanted a platform whose sensing, power, interfaces, and software architecture I could design myself. Atlas combines flight data acquisition, telemetry, deployment outputs, actuator support, and expansion on one board. It is intended to support practical rocketry work as well as experiments in state estimation and control.',
 'I chose an STM32H743ZIT6 with an ARM Cortex-M7 core for its processing capacity, I/O count, and communication peripherals. The processor needs to coordinate sensor acquisition, storage, communications, and outputs while leaving room for more demanding filtering and control software. USB and SWD provide two development and recovery paths.',
 'The layout below is the actual functional map from my design documentation. Power conversion is concentrated toward the bottom; the MCU and supporting components occupy the center; sensors, radio modules, and connectors are distributed around those core functions.'
 ])+figure('record-55-0','Annotated Atlas layout, showing the actual power, processor, sensor, RF, connectivity, status, and deployment regions.','portrait')+table('The system at a glance',['Function','Implementation','Purpose'],[
 ['Processing','STM32H743ZIT6 · Cortex-M7','Coordinate acquisition, logging, communication, outputs, and future estimation software.'],
 ['Power','Protected battery input; 3.3 V logic, auxiliary 3.3 V, 5 V, and 8.4 V rails','Supply digital electronics, external peripherals, and actuator loads at appropriate voltages.'],
 ['Actuation','Eight PWM outputs and five deployment channels with continuity sensing','Support mechanisms and deployment experiments while monitoring channel readiness.'],
 ['Development','USB-C, SWD, status LED, buzzer, and switches','Configuration, programming, debug access, and visible or audible system status.']
 ])},
 {id:'sensing',nav:'Sensors, timing & telemetry',title:'Complementary measurements, several ways to get the data back.',html:({paragraphs,table,figures})=>paragraphs([
 'The sensor suite deliberately combines different measurement types and dynamic ranges. Orientation, ordinary inertial motion, high acceleration, magnetic field, pressure, and GNSS position each describe a different part of the vehicle state. The architecture is intended to support an extended Kalman filter, but successful sensor communication is only the first step toward validated state estimation.'
 ])+table('Sensing and timing hardware',['Device','Role'],[
 ['BNO085','Absolute orientation sensing.'],['LSM6DSV16BTR','Inertial measurement unit for acceleration and angular motion.'],['KX134-1211','High-g acceleration measurement.'],['MMC5983MA','Magnetic-field measurement for heading-related work.'],['MS561101BA03-50','Barometric pressure measurement for altitude and flight-phase analysis.'],['MAX-M10S','GNSS position, velocity, and pulse-per-second timing.']
 ])+paragraphs([
 'The communications paths serve different operating conditions. USB-C supports the bench and wired configuration. A NINA-B112-04B BLE module supports short-range communication. A UART LoRa expansion connector provides a long-range telemetry path. The microSD interface preserves a complete onboard record even when radio reception is unavailable.',
 'External SPI, I²C, UART, GPIO, switched inputs, and protected power connections keep Atlas useful beyond one rocket configuration. The onboard program uses the MCU’s internal program memory, while the SD card is available for logs and larger data such as lookup tables.'
 ])+figures([['record-45-0','STM32 pin allocation used to organize the board’s peripheral and I/O requirements.','drawing'],['record-46-0','An early layout experiment before the more organized Atlas board revisions.']])},
 {id:'prototype',nav:'The bare-board decision',title:'Finding expensive mistakes on an inexpensive prototype.',html:({paragraphs,figures,note})=>paragraphs([
 'The first complete layout looked ready to send for assembly, but the cost changed my prototyping strategy. A fully assembled board was estimated at more than $700 including parts, and the minimum order was two. I ordered bare PCBs first so I could examine the physical result before committing to components and assembly.',
 'I checked for unintended shorts and connections, pad dimensions, footprint compatibility, silkscreen mistakes, and via-in-pad concerns. That inspection found real design errors: three incorrect footprints, mislabeled silkscreen, and unintended pad connections around the SD-card, USB protection, and deployment circuitry. These were issues worth finding before assembly, not while trying to debug an expensive populated board.'
 ])+figures([['record-48-0','The first complete PCB revision, reverse side.','drawing'],['record-49-0','The first complete PCB revision, front side.','drawing'],['record-50-0','Routing in the first complete revision.','drawing']],'three boards')+figures([['record-52-0','Manufactured bare PCB, reverse side.','portrait'],['record-53-0','Inspecting the bare board before component assembly.','portrait'],['record-54-0','Front-side pads and silkscreen on the first physical board.','portrait']],'three boards')+note('The design decision','The bare-board run turned a high-cost assembly commitment into a smaller inspection step. Its value was concrete: footprint, connectivity, and labeling errors could be corrected while the board was still inexpensive to revise.')},
 {id:'revision',nav:'Revising the board',title:'Organizing power, signals, and field connections.',html:({paragraphs,figures})=>paragraphs([
 'I reviewed the whole design after the bare-board inspection, changed connections and selected components, and produced the revised board. The organization had to work electrically and physically: sensitive sensing and digital functions, higher-current outputs, radio hardware, and connectors all shared a limited footprint.',
 'The protected input feeds dedicated regulators for the required rails. The MCU region includes its oscillators and supporting capacitors. The deployment section brings the five channels, continuity-sensing components, and physical-connect safety interface to screw terminals. Other terminals and headers expose the serial buses and general-purpose I/O.',
 'I also kept field usability in the design. The buzzer, RGB indicator, switches, and accessible connectors give software ways to communicate readiness and faults and give me ways to service the board. Their final behavior depends on firmware; a connector or output capability alone is not a completed flight feature.'
 ])+figures([['record-57-0','Revised front-side design.','drawing'],['record-58-0','Angled view of the revised board and connector arrangement.','drawing']],'boards')+figures([['record-59-0','Revised routing and board organization.','drawing'],['record-60-0','Revised reverse side.','drawing']],'boards')},
 {id:'bring-up',nav:'Assembled-board testing',title:'From a manufactured board to working subsystems.',html:({paragraphs,figures,table})=>paragraphs([
 'The assembled boards have now arrived. Bring-up has moved the project beyond CAD and bare-board inspection: I have checked the MCU, clocks, power conversion, sensing, communications, storage, and outputs with the physical hardware.',
 'The sensors report clean data. All eight PWM outputs have operated concurrently under load. Power regulation and ADC power readings work, and the deployment channels passed functional checks. The GNSS receiver acquired nine satellites indoors; LoRa sent clean packets in both directions. These are useful bench results, while still leaving the flight environment to be tested.'
 ])+figures([['record-64-0','Complete two-system Atlas load test on the dorm workbench.'],['record-66-0','Fully connected rocket-side Atlas for a load test.','portrait']])+table('Current bring-up record',['Subsystem','Observed result'],[
 ['Processor & programming','MCU and clock signals functional; firmware loading over USB-C and SWD successful.'],
 ['Power & outputs','Regulators and ADC power monitoring functional; all eight PWM channels operated together under load; deployment channels functional.'],
 ['Sensing & GNSS','Clean sensor data; nine-satellite GNSS acquisition indoors.'],
 ['Wired interfaces','USB-C operates in both orientations; external SPI, I²C, UART, GPIO, and switches functional.'],
 ['Wireless links','BLE functional; LoRa packets transmitted and received.'],
 ['Storage & status','SD-card reads and writes successful; buzzer functional. RGB LED requires component rework.']
 ])+figures([['record-61-0','Unconnected single Atlas system hero photo.','portrait'],['record-62-0','Complete single Atlas system packed for transport to the lab.','portrait'],['record-65-0','Power, communications, and test equipment on the workbench.']],'three')},
 {id:'remaining',nav:'The LED fault & next steps',title:'What works, what does not, and what is still unproven.',html:({paragraphs,figures,note})=>paragraphs([
 'The RGB LED is the outstanding hardware fault. I selected MOSFETs with the source and drain reversed for the intended circuit. The MCU control signals have been confirmed, so the correction is a component-level rework rather than a change to the processor. Replacement parts still need to be soldered onto the board.',
 'Atlas is bench tested, not yet flight qualified. Sensor fusion, launch and apogee detection, calibration routines, state estimation, control experiments, and the final operational logic remain software-development objectives. Environmental testing and integrated flight validation are also still ahead.',
 'For Unknown Rider, the intended role is an independent backup and data-acquisition platform alongside established recovery computers. That gives Atlas a path into flight experiments while preserving a separate primary recovery architecture.'
 ])+figures([['record-68-0','Complete two-system Atlas ready for field testing.','portrait']])+note('Current status','Major subsystems are functioning on the bench. The RGB LED needs rework; flight-software validation and environmental qualification are not yet complete.')}
 ]
};
