export default {
 cover:'record-11-0',
 coverCaption:'The Gladius III team at FAR Unlimited 2025. The 11-foot vehicle flew on an AeroTech N1000W and finished third.',
 ownership:'As a structures member, I owned the motor-selection and aerodynamic-profile simulations, designed and helped manufacture fins and bulkheads, integrated the motor, and conducted final assembly. I performed several structural analyses and used the team’s master CAD extensively; I did not create the entire vehicle model or every FEA result shown here.',
 source:'Engineering Portfolio Raw, pp. 1–15; August 28, 2026 résumé. Motor-trade outputs used an early mass model. The 17,180 ft prediction refers to the final model. FEA figures and master CAD include team contributions.',
 sections:[
 {id:'motor',nav:'Motor selection',title:'Choosing the ascent, not just the motor.',html:({paragraphs,table,figure})=>paragraphs([
 'Gladius III was a 70-pound, 11-foot competition rocket carrying water ballast, an experiment on epoxy behavior under acceleration and vibration, and redundant recovery avionics. It became my first substantial opportunity to connect simulation, manufacturing, and a real competition flight.',
 'The motor trade began before the full vehicle was designed. I used mass analogs and approximate aerodynamic properties with OpenRocket, RASAero II, and SolidWorks models to compare candidate trajectories. We wanted altitude, but peak velocity, acceleration, stability, and price all constrained the choice. Faster ascent also moved the center of pressure forward and threatened stability margins.',
 'The N1000W provided the balance we needed: a slow burn, a manageable ascent profile, a subsonic prediction, and an affordable motor. Its early-model peak acceleration was 62.8 m/s², compared with 293 m/s² for the M6000ST. The choice reduced the severity of the loads the structure and payloads would have to survive.'
 ])+table('Early motor trade · mass-analog model',['Motor','Impulse<br>N·s','Apogee<br>m','Peak speed<br>m/s','Peak accel.<br>m/s²','Flight time<br>s','To apogee<br>s','Stability<br>cal / %'],[
 ['N3300R','14,035','5,018','441','125','138','29.7','1.23 / 5.84'],
 ['N2220DM','10,831','3,832','334','96','114','27.1','1.28 / 6.09'],
 ['N2200W','13,263','4,742','367','92.7','134','29.8','1.25 / 5.93'],
 ['M6000ST','9,606','3,520','381','293','107','24.6','1.59 / 7.55'],
 ['N1000W · selected','14,138','5,347','306','62.8','147','34.3','1.19 / 5.64'],
 ['N4000W-PS','18,279','6,423','516','144','158','33','1.42 / 6.77'],
 ['M1939W','10,369','3,931','323','81.4','120','27.7','1.36 / 6.40'],
 ['N1975W-PS','13,822','4,940','378','93.5','138','30.3','1.35 / 6.38'],
 ['M2000R','9,186','3,415','317','86.2','109','25.8','1.35 / 6.41'],
 ['O5500X-PS','21,395','7,843','613','240','180','35.2','1.51 / 7.18']
 ])+paragraphs(['These figures belong to the preliminary comparison, not the final flight prediction. The selected N1000W case estimated a 34.3-second time to apogee, a 147-second total flight time, and a 1.19-caliber stability value in that model. The completed vehicle was later predicted to reach 17,180 feet.'])+figure('record-02-0','The early N1000W OpenRocket profile: altitude, vertical velocity, and vertical acceleration through ascent and recovery.','drawing')},
 {id:'interfaces',nav:'CAD & structural interfaces',title:'Using the common model to make buildable parts.',html:({paragraphs,figure,figures})=>paragraphs([
 'The team’s master CAD provided a common dimensional baseline for analysis, manufacturing, and assembly order. I worked with it extensively for CFD and fabrication even though I did not author the complete model. The model captured the nose cone, airframe, fins, motor tube, retaining hardware, centering rings, bulkheads, and payload regions.',
 'The bulkheads did much more than divide the tube. They secured experiments, payloads, avionics, recovery hardware, and ejection charges, and included sealed passages for data cables and deployment leads. We combined structural analysis with the flight and aerodynamic loads to assess the interfaces and the components they carried.',
 'I helped design and manufacture the bulkheads from quarter-inch G12 fiberglass on the waterjet. The drawings translated the model into hole locations, diameters, and material geometry that the assembly actually depended on.'
 ])+figure('record-04-0','The team’s complete vehicle model, used as the shared reference for dimensions, analysis, and assembly.','drawing slim')+figures([['record-03-0','Manufacturing drawing for one G12 bulkhead.','drawing'],['record-03-1','A second bulkhead drawing, with its own mounting and clearance features.','drawing']])},
 {id:'structure',nav:'Fin & airframe analysis',title:'A previous fin failure made the load path matter.',html:({paragraphs,figures,note})=>paragraphs([
 'Gladius II had lost its fins to aerodynamic loading, so the fin attachment could not be treated as a routine detail. The structural study compared notched and notchless attachment models, examining normal stress, shear stress, displacement, and strain. Aerodynamic models supplied estimated component loads; the FEA results were used to assess whether the geometry and materials could survive them with margin.',
 'The study also varied the solver setup, including large-displacement and soft-spring configurations. I ran several of these analyses, while the selected pairs below reflect the team’s structural work. Each pair compares notchless and notched attachments using the large-displacement configuration, grouped by the quantity being examined.'
 ])+'<h3>Normal-stress comparisons</h3>'+figures([['record-05-0','Notchless fin attachment: Z normal stress, large-displacement analysis.','drawing'],['record-05-2','Notched fin attachment: Z normal stress, large-displacement analysis.','drawing']],'analysis')+'<h3>Shear-stress comparisons</h3>'+figures([['record-06-0','Notchless fin attachment: XZ shear stress, large-displacement analysis.','drawing'],['record-06-2','Notched fin attachment: XZ shear stress, large-displacement analysis.','drawing']],'analysis')+'<h3>Displacement and strain</h3>'+figures([['record-07-0','Notchless fin attachment: Z displacement, large-displacement analysis.','drawing'],['record-07-2','Notched fin attachment: Z displacement, large-displacement analysis.','drawing']],'analysis')+figures([['record-07-4','Notchless fin attachment: Z strain, large-displacement analysis.','drawing'],['record-07-5','Notched fin attachment: Z strain, large-displacement analysis.','drawing']],'analysis')+paragraphs([
 'For the aft airframe, we also asked what would happen if the fins no longer contributed structural support. One compression model included their stiffness; another deliberately removed that contribution. The second case was important because partial joint failure should not immediately become body-tube collapse and motor release.',
 'The documented analysis reported less than 0.01 mm maximum deformation with the fins contributing and less than 1 mm in the model that neglected their support. Those were model results under the selected loads. They supported the design decision, while the flight itself remained the integrated test.'
 ])+figures([['record-08-2','Aft-airframe compression model with fin support.','drawing'],['record-09-0','Conservative compression model that neglects the fins’ structural contribution.','drawing']])},
 {id:'manufacture',nav:'Bonding & integration',title:'Making the joints the model assumed.',html:({paragraphs,figures})=>paragraphs([
 'Analysis was only useful if the finished bonds and interfaces resembled what had been modeled. I experimented with epoxy cure methods, surface preparation, and timing to improve fin strength for the weight added. I also designed and manufactured fins and bulkheads, then integrated the motor and helped bring the full vehicle through final assembly.',
 'This was the point where manufacturing and system knowledge became inseparable. A bulkhead’s location affected payload and recovery space; fin alignment affected aerodynamic behavior; and a bond’s quality determined whether the assumed load path actually existed.'
 ])+figures([['record-12-0','Preparing the motor hardware for integration.'],['record-15-0','The finished aft airframe and fin assembly.']])},
 {id:'result',nav:'Flight & model comparison',title:'17,172 feet—and an intact recovery.',html:({paragraphs,figures,note})=>paragraphs([
 'Gladius III flew to 17,172 feet and placed third at FAR Unlimited 2025. I tracked the vehicle and joined the desert recovery. The final preflight model predicted 17,180 feet, only 8 feet above the measured result.',
 'That is approximately 0.047% difference for this one apogee comparison. It was a strong result, but not a general accuracy guarantee for the simulation tools or every output in the model. The defensible comparison is specific: this vehicle, this flight, and the final predicted and measured apogees.',
 'The project gave me a practical foundation in motor trades, structural analysis, composite assembly, and launch integration. It also set up the next design step: Apollyon’s fin attachment moved away from slots, supported by physical joint tests and a deliberate alignment fixture.'
 ])+figures([['record-10-0','Gladius III leaving the launch rail.'],['record-14-0','The recovered vehicle in the desert.']])+figures([['record-13-0','Gladius III returned to the lab after the flight.']],'natural')}
 ]
};
