export default {
 coverCaption:'Hat Trick on the launch rail. The 68-inch vehicle uses a 3-inch fiberglass airframe and a 54 mm motor mount.',
 ownership:'I designed, manufactured, assembled, instrumented, and flew Hat Trick independently. I owned the structure, avionics packaging, recovery integration, launch preparation, and the investigation and rebuilding between six flights.',
 source:'Project account and flight record: Engineering Portfolio Raw, pp. 33–42; August 28, 2026 résumé. Altitudes are recorded flight outcomes, and the troubleshooting sequence follows the original flight log.',
 sections:[
 {id:'build',nav:'Building the airframe',title:'Making every interface my responsibility.',html:({paragraphs,figures})=>paragraphs([
 'Hat Trick began as my independent Level 2 rocket and a way to build the experience needed for a future Level 3 design campaign. The name came from an initial plan to fly three configurations. It became a six-flight program that taught me considerably more than three straightforward successes would have.',
 'The vehicle is 68 inches long, with a 3-inch fiberglass airframe, G10 components, a 54 mm motor mount, and dual deployment. I started with the bonded interfaces: preparing the nose cone, couplers, centering rings, fins, bulkheads, body tubes, and motor tube before assembly. Custom printed and laser-cut jigs supported the parts during machining and bonding.',
 'Machining included the airframe pressure-release holes, fastener locations, coupler interfaces, and recovery-hardware mounting points. I prepared and test-fitted the bulkhead fittings and connecting hardware alongside the structure so that the finished airframe would accept the actual recovery and avionics equipment.'
 ])+figures([['record-34-0','Airframe and motor-mount work on the fabrication bench.'],['record-34-1','Machined G10 bulkheads and attachment holes.'],['record-34-2','Machining and tapping the fiberglass airframe for pressure release, mounting, and shear-pin screws.'],['record-34-3','Complete airframe after machining operations.','portrait']])},
 {id:'joints',nav:'Joints, alignment & assembly',title:'Designing the assembly process around alignment.',html:({paragraphs,figures})=>paragraphs([
 'After bonding the couplers and motor-mount centering rings, I installed the motor-tube assembly inside the aft airframe. The fins were the most alignment-sensitive part of the build. I used three separate jigs to keep the G10 fins positioned while bonding them through the airframe slots to the motor mount, then added exterior fillets after the internal joints cured.',
 'The motor retainer, rail guides, and recovery hardware completed the mechanical system. A long straightedge established the rail-guide alignment. The shock cords, parachutes, flame protection, shear pins, and quick connections had to fit and move correctly as a complete recovery assembly, not just as individual components.'
 ])+figures([['record-35-0','The aft airframe held in alignment fixtures during fin bonding.'],['record-35-1','Looking into the assembled nose cone.'],['record-35-2','Epoxying together the airframe, couplers, and internal assemblies.'],['record-35-3','Longitudinal alignment and assembly work.','portrait']])+figures([['record-37-0','The painted vehicle before final field integration.','portrait'],['record-37-1','Full rocket after painting, before stenciling.','portrait'],['record-37-2','Hat Trick before stenciling.']],'three')},
 {id:'avionics',nav:'Recovery & avionics',title:'Twenty sled revisions inside a nine-inch coupler.',html:({paragraphs,figure,figures})=>paragraphs([
 'The avionics bay had to fit inside a 9-inch coupler while keeping wiring and deployment connections accessible. The printed sled went through roughly 20 revisions as I worked through packaging and the lessons from each flight.',
 'A BlueRaven provided altitude corroboration, a Fluctus flight computer handled primary altitude determination, tracking, and telemetry, and a Featherweight GPS tracker supplied an independent tracking path. These were complementary sensing and tracking devices; they were not three identical recovery controllers. WAGO quick connections made the ejection-system interface easier to assemble and service.',
 'The two recovery events used different mechanisms. The motor’s black-powder charge released the drogue, while a Peregrine black-powder-actuated CO₂ puncture system deployed the main. Across the flight program, I had to work through event detection, pressure retention, mechanical separation, and physical protection of the electronics.'
 ])+figures([['record-36-0','My dorm room the day before a launch.'],['record-36-1','Previous-generation 3D-printed avionics bay examples.'],['record-36-2','Preparing the vehicle, tools, and field equipment.']],'three')+figure('record-41-0','Packed avionics and field-support equipment.')},
 {id:'flights',nav:'Six flights & what changed',title:'The flight log became the design history.',html:({paragraphs,figure,table})=>paragraphs([
 'The first flight ended in a ballistic impact because a machine screw had been installed where a shear pin was required. The rocket could not separate. That was a preparation error with a structural consequence: I rebuilt the forward airframe and avionics bay, then improved the launch procedure and parachute packing.',
 'The second failure was different. Ejection gas escaped through a gap between adapter plates, so the system could not develop enough pressure to separate. I pressure-sealed the bays, revisited the structure, and redesigned the avionics package with greater attention to crash resistance. The next two flights recovered the vehicle but deployed the main too high—first because of flight-computer configuration, then because the drogue event also broke the main-retention pins.'
 ])+figure('record-39-0','The aftermath of the first ballistic flight. Recovery failure drove a forward-airframe rebuild and changes to launch preparation.','portrait')+table('The complete six-flight record',['Flight / motor','Apogee','What happened','What changed'],[
 ['01 · J270W','3,376 ft','Ballistic impact. A machine screw prevented the intended separation.','Rebuilt the forward airframe and avionics bay; improved launch procedures and packing.'],
 ['02 · J270W','3,267 ft','Ballistic impact. Gas escaped through an adapter-plate gap.','Pressure sealing, structural refits, and another avionics-bay redesign with impact protection.'],
 ['03 · J270W','3,214 ft','Main deployed too high. The flight computer was too reactive near maximum velocity.','Revised the avionics stack, bay, and configuration.'],
 ['04 · J425R','3,913 ft','Main deployed too high. Excess drogue-event pressure broke the main shear pins.','Avionics overhaul and retuned ejection charges.'],
 ['05 · J250W','4,071 ft','Full success.','No change required.'],
 ['06 · K535W','6,943 ft','Full success, on the same day as flight 05.','The system repeated its recovery sequence at higher motor energy.']
 ])},
 {id:'result',nav:'What carried forward',title:'A recovery system I understood through failure.',html:({paragraphs,figure})=>paragraphs([
 'Flights five and six both completed their intended recovery sequence. The final flight reached 6,943 feet on a K535W, with no changes required between the two successful flights that day.',
 'The program changed how I reason about reliability. A failed recovery does not necessarily mean a failed flight computer: a fastener, leak path, configuration setting, or interaction between separation events can produce the same outward result. The useful work was isolating those causes, inspecting the recovered hardware, and making changes that addressed the actual mechanism.',
 'That experience became immediately useful on Apollyon I, where I rebuilt the recovery avionics at the competition site. Hat Trick gave me both an architecture to adapt and a practical understanding of the interfaces that had already caused trouble.'
 ])+figure('record-33-1','T-minus 2 minutes.','portrait')}
 ]
};
