export default {
 coverCaption:'Preliminary Unknown Rider vehicle model. The project is in design development around the AeroTech N1000W; this is a simulation model, not completed hardware.',
 ownership:'Unknown Rider is my independent Level 3 certification project. I am developing the vehicle architecture, aerodynamic and structural analyses, recovery concept, avionics integration, and manufacturing plan. The current design is being revised following the change from the unavailable CTI N5800 to the AeroTech N1000W.',
 source:'Engineering Portfolio Raw, pp. 69–72; Parts List N1000W.xlsx; current project update. The N1000W parts plan and earlier written architecture contain different avionics selections, so those choices are presented as evolving design work. Targets and costs are planning values.',
 sections:[
 {id:'revision',nav:'The N1000W redesign',title:'An unavailable motor changed the design basis.',html:({paragraphs,note})=>paragraphs([
 'Unknown Rider is intended to be both my Level 3 certification vehicle and a platform for high-altitude avionics experiments. The original CTI N5800 plan could not proceed because the motor was unavailable, so I am redesigning around the AeroTech N1000W. That changes the mission profile and requires the structure, stability, and recovery assumptions to be revisited together.',
 'The current written concept describes a 4-inch-diameter vehicle, approximately 103 inches tall and 43 pounds. Preliminary N1000W simulations target about 50,000 feet and a peak speed near Mach 2. These remain revision-dependent predictions; Unknown Rider has not established those values in flight.'
 ])+note('Current design basis','AeroTech N1000W · preliminary design and analysis. The earlier N5800-based speed target is superseded and is not carried forward as the current vehicle specification.')},
 {id:'structure',nav:'Structure, heating & RF',title:'The material choices have to serve more than strength.',html:({paragraphs,table})=>paragraphs([
 'The concept uses a carbon-fiber primary airframe for stiffness and strength, with fiberglass where radio transparency is needed. A long, 7.2:1 fiberglass nose cone houses tracking equipment, while a custom aluminum tip is intended to address the nose region’s thermal and structural demands and contribute forward mass for stability.',
 'The N1000W parts plan specifies 2024-T3511 aluminum stock for that tip, refining the material reference in the earlier prose. It also includes half-inch quasi-isotropic carbon-fiber plate for the fins, structural epoxy, and supplies for a fiberglass nose-cone layup. Fin fillets and overwrap are part of the structural concept.',
 'The point is to treat stiffness, heating, radio performance, stability, and manufacture as coupled choices. Adding carbon reinforcement indiscriminately would work against the tracker’s radio path; adding forward mass changes stability but also changes the trajectory and recovery loads.'
 ])+table('Current material and manufacturing plan',['Area','Planned approach'],[
 ['Aft airframe','Carbon-fiber tube and reinforcing coupler.'],['Forward / avionics region','G12 fiberglass tube and couplers, preserving RF-compatible regions.'],['Nose cone','Fiberglass layup over custom tooling; aluminum tip.'],['Fins','Half-inch quasi-isotropic carbon-fiber plate, bonded and reinforced.'],['Internal interfaces','Aluminum bulkplates, printed components, and standard mounting hardware.']
 ])},
 {id:'analysis',nav:'Simulation & design review',title:'Closing the model before committing to the build.',html:({paragraphs,figure})=>paragraphs([
 'The design work uses COMSOL, RASAero II, OpenRocket, MATLAB, Simulink, and SolidWorks to examine stability, aerodynamic loading, thermal behavior, structural margins, and recovery. The motor change means these checks need to remain tied to the same configuration rather than mixing results from different revisions.',
 'The trajectory below is part of the preliminary design record. It provides a starting point for the mission profile and for identifying the conditions the airframe and electronics will have to survive. Fabrication follows the major analysis and design-review milestones; the vehicle is still in development.'
 ])+figure('record-71-0','Preliminary flight simulation and associated output table from the N1000W design record.','drawing')},
 {id:'recovery',nav:'Recovery & avionics evolution',title:'Keeping the experimental electronics in context.',html:({paragraphs,note})=>paragraphs([
 'The written recovery concept uses CO₂-based deployment for the high-altitude environment, two BlueRaven flight computers for primary recovery, and Atlas as an independent backup and data-acquisition platform. It also describes redundant tracking through GPS and a separate RF path.',
 'The newer N1000W procurement draft includes an Atlas-derived computer called Kronos and a Swift GPS tracker, with the additional RF-tracking hardware deferred. Those selections show that the electronics package is evolving alongside the motor change. They should not be read as a fully resolved, assembled replacement for the earlier recovery architecture.',
 'The planned hardware budget also includes separate forward and aft deployment systems, a drogue and main parachute, shock cords, swivels, and quick links. The final design still needs to reconcile those hardware choices with recovery loads, bay packaging, and the configuration that will actually fly.'
 ])+note('The distinction that matters','Atlas has functioning bench hardware. Unknown Rider’s complete avionics and recovery configuration is still being developed and has not been validated in flight.')},
 {id:'procurement',nav:'Procurement & next milestones',title:'A build plan with the expensive decisions visible.',html:({paragraphs,table})=>paragraphs([
 'My N1000W bill of materials totals approximately $10,000 including its tax and shipping allowance. It tracks quantities, purpose, and procurement status, so the design can be examined as something that must be purchased, manufactured, and assembled. The listed items are not marked ordered or arrived in that planning sheet.',
 'The largest commitments include the motor hardware and reload, carbon-fiber stock, avionics, and recovery equipment. Separating those commitments makes changes in the mission architecture visible in the budget before they become purchased hardware.'
 ])+table('Selected line items from the N1000W planning sheet',['Item','Planned cost'],[
 ['RMS98/15360 motor hardware','$1,352.00'],['N1000W-PS reload','$1,409.00'],['Carbon-fiber fin stock, two plates','$860.68'],['Atlas-derived Kronos computer allowance','$1,000.00'],['Main and drogue parachutes','$568.82'],['Tax and shipping allowance','$950.23'],['Complete planning-sheet total','$10,000.07']
 ])+paragraphs(['The next milestones are to reconcile the updated configuration, complete the supporting analysis and design reviews, fabricate and integrate the structure, and validate the recovery and electronics as an assembled system. Hat Trick and Apollyon inform that sequence: the flight computer, mechanical interfaces, pressure paths, and launch procedure have to be evaluated together.'])}
 ]
};
